include $(GOROOT)/src/Make.inc

TARG=gform
GOFILES=\
	init.go\
	rect.go\
	color.go\
	font.go\
	imagelist.go\
	globalvars.go\
	util.go\
	canvas.go\
	icon.go\
	msghandlerregistry.go\
	controller.go\
	eventhandler.go\
	eventarg.go\
	eventmanager.go\
	controlbase.go\
	wndproc.go\
	w32control.go\
	dialog.go\
	form.go\
	customcontrol.go\
	buttons.go\
	statics.go\
	edit.go\
	progressbar.go\
	commondlgs.go\
	listview.go\
	tooltip.go\
	app.go
	
include $(GOROOT)/src/Make.pkg
